//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szkola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisy
    {
        public int ZapisyID { get; set; }
        public int StudentID { get; set; }
        public int PrzedmiotID { get; set; }
        public string Data_zapisu { get; set; }
    
        public virtual Przedmiot Przedmiot { get; set; }
        public virtual Student Student { get; set; }
    }
}
